### ISSUE TITLE
Indexer sets img and thumb paths incorrectly for transcript files that end in .html

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/ddr-cmdln#187]
The indexer is hard-coded to append `.htm` to the paths for the `img` and `thumb` attributes when the `File` is a `transcript` role and has the mimetype `text/html`. This means that if a transcript is uploaded with an `.html` extension, the data for `img` and `thumb` is malformed, and the download link for the transcript is broken in the `ddr-public` interface.  

See: https://github.com/denshoproject/ddr-cmdln/blob/e37a48aefc7a9fad71bffb20a0ab742bc74b3521/ddr/DDR/models/common.py#L314

@GeoffFroh has already developed a patch and tested (based on https://github.com/denshoproject/ddr-cmdln/blob/e37a48aefc7a9fad71bffb20a0ab742bc74b3521/ddr/DDR/models/common.py#L331).

**Comment by GeoffFroh** [comment]
Fixed in 191a95c019fc080fa705797e425caa43668a4061

**Comment by GeoffFroh** [comment]
Merged to `master` 5.0.7 in 3e9f54e443568a44e03108e73dd56f49e3f7527b

**Comment by gjost** [comment]
Included in packages ddrcmdln-master_5.0.7~deb10 and ddrlocal-master_5.0.7~deb10.
