### ISSUE TITLE
Does ddrindex care if mpeg removed from IArchive?

### ISSUE THREAD

**Issue by gjost** [denshoproject/ddr-cmdln#191]
In the ddr publication workflow, the `ddrindex` command calls code in the `archivedotorg` module (https://github.com/denshoproject/ddr-cmdln/blob/34cbb51b4acf364e90d06e7e8f4b97f52ca0124a/ddr/DDR/archivedotorg.py), which then  retrieves metadata from IA about the binary files stored there. This info is attached to the object, which `ddrindex` then pushes to the ES index. 

However, some segment objects stored at IA do not have `mpg` mezzanine files because of licensing/usage restrictions. Will this cause issues with `ddrindex`?

To test, the `mpg` file has been removed from: `ddr-densho-122-23-23` (https://archive.org/details/ddr-densho-122-23-23)

See also: https://github.com/denshoproject/ddr-public/issues/163

**Comment by GeoffFroh** [comment]
@sarabeckman: Please try indexing sample `ddr-densho-122` VH entities to the staging cluster to confirm that missing MPEG2s are OK.

**Comment by sarabeckman** [comment]
`ddr-densho-122` has been indexed on ddrstage https://ddrstage.densho.org/interviews/ddr-densho-122-6-1/ 

I'm seeing the wrong video player(IA videoplayer) plus I still see both video download buttons. Clicking either button doesn't start a download on either Windows or MacOS.

**Comment by gjost** [comment]
I didn't pull the new code on ddrstage.  i'll do that in a bit.

I ran `ddrindex` on `ddr-densho-122-4` and didn't see any problems.
