### ISSUE TITLE
`ddrindex publish` adds incorrect mpg and ogv download links to ES segment docs

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/ddr-cmdln#195]
`ddrindex publish` is erroneously adding mpg and ogv download attributes to segment docs in the ES index when the following conditions are met:

- the segment does **not** have mpg2/ogv binaries at IA (i.e., they have been purposefully removed for copyright/access reasons)
- the entire parent collection for the segment is indexed,  and 
- some segments in the parent collection have mp2/ogv binaries available at IA 

e.g., `ddrindex publish ddr-densho-122`

In the case that we observed (ddr-densho-122), all of the segment docs where the error occurred had exactly the same IA mpg/ogv data values inserted (`https://archive.org/download/ddr-densho-122-28-2/ddr-densho-122-28-2-mezzanine-6571604160.mpg`). 

Here is an example of a snippet from the ES doc for `ddr-densho-122-24-2`:
<pre><code>
        "ia_meta": {
            "id": "ddr-densho-122-24-2",
            "xml_url": "https://archive.org/download/ddr-densho-122-24-2/ddr-densho-122-24-2_files.xml",
            "http_status": 200,
            "original": "ddr-densho-122-24-2-mezzanine-f1b8169a23.mpg",
            "mimetype": "video/mpeg",
            "files": {
                "mp3": {
                    "name": "ddr-densho-122-24-2-mezzanine-f1b8169a23.mp3",
                    "format": "mp3",
                    "url": "https://archive.org/download/ddr-densho-122-24-2/ddr-densho-122-24-2-mezzanine-f1b8169a23.mp3",
                    "mimetype": "audio/mpeg",
                    "encoding": null,
                    "sha1": "f3410330d13461173ac6657b79f68aa9c853c4a4",
                    "size": "1478656",
                    "length": "02:03",
                    "height": "0",
                    "width": "0",
                    "title": ""
                },
                "mp4": {
                    "name": "ddr-densho-122-24-2-mezzanine-f1b8169a23.mp4",
                    "format": "mp4",
                    "url": "https://archive.org/download/ddr-densho-122-24-2/ddr-densho-122-24-2-mezzanine-f1b8169a23.mp4",
                    "mimetype": "video/mp4",
                    "encoding": null,
                    "sha1": "f6e8f17bc431633e6132f3fc3575d33729f6cb6e",
                    "size": "12823685",
                    "length": "123.14",
                    "height": "480",
                    "width": "640",
                    "title": ""
                },
                "png": {
                    "name": "ddr-densho-122-24-2-mezzanine-f1b8169a23.png",
                    "format": "png",
                    "url": "https://archive.org/download/ddr-densho-122-24-2/ddr-densho-122-24-2-mezzanine-f1b8169a23.png",
                    "mimetype": "image/png",
                    "encoding": null,
                    "sha1": "3c013d321bde89b2275ef0dfaadc42b4b9f23c9c",
                    "size": "12094",
                    "length": "",
                    "height": "",
                    "width": "",
                    "title": ""
                },
                "mpg": {
                    "name": "<b>ddr-densho-122-28-2-mezzanine-6571604160.mpg</b>",
                    "format": "mpg",
                    "url": "<b>https://archive.org/download/ddr-densho-122-28-2/ddr-densho-122-28-2-mezzanine-6571604160.mpg</b>",
                    "mimetype": "video/mpeg",
                    "encoding": null,
                    "sha1": "6571604160386067260eea3964889fca59436f64",
                    "size": "257628164",
                    "length": "322.92",
                    "height": "480",
                    "width": "640",
                    "title": ""
                },
                "ogv": {
                    "name": "<b>ddr-densho-122-28-2-mezzanine-6571604160.ogv</b>",
                    "format": "ogv",
                    "url": "<b>https://archive.org/download/ddr-densho-122-28-2/ddr-densho-122-28-2-mezzanine-6571604160.ogv</b>",
                    "mimetype": "video/ogg",
                    "encoding": null,
                    "sha1": "ee30a5d5a9d18bfafc480d40ba296d20385c790e",
                    "size": "24002562",
                    "length": "322.92",
                    "height": "300",
                    "width": "400",
                    "title": ""
                }
            }
        },
</code></pre>

In the example above, the `mpg` and `ogv` attributes should not be present.

**Comment by gjost** [comment]
Fixed in `ddr-cmdln` commit `07a77ce` for package `ddrcmdln-master_5.0.18~deb10` (forthcoming).

Problem was a nice little gotcha in Python: if you define a variable in a class, outside of class methods, then the variable belongs to the class not the object(s).  For most objects this was no problem, as all the key/value pairs in `IAObject.files` get repopulated for each object.  But in `ddr-densho-122` there is precisely one MPEG2 file (`ddr-densho-122-28-2`).  It "stuck" there because no subsequent object overwrote that value.  Initializing `IAObject.files` for each object solves the problem.
