### ISSUE TITLE
Tif files not being converted into access jpg successfully

### ISSUE THREAD

**Issue by sarabeckman** [denshoproject/ddr-cmdln#201]
Tif files in two collections, ddr-sbbt-3 and ddr-csujad-29 are not successfully creating access jpg files. I have tried both deleting the file and reuploading which did not fix issue. I also have tried the "generate new access file" button which also did not fix the issue. 

Jost suggested trying `convert /path/to/IMAGENAME.tif  /tmp/IMAGENAME.jpg`. I tried this on both my local VM (V5.0.16_HQMA) and Maunakea (10.0.1.17) and got this message:
`(cmdln) ddr@maunakea:/media/qnfs/kinkura/working/Problem_Tifs$ convert ./ddr-sbbt-3-28-mezzanine-e9670899fa.tif ./ddr-sbbt-3-28-mezzanine-e9670899fa.jpg
convert-im6.q16: Incompatible type for "RichTIFFIPTC"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/949.
convert-im6.q16: width or height exceeds limit `./ddr-sbbt-3-28-mezzanine-e9670899fa.tif' @ error/cache.c/OpenPixelCache/3912.
convert-im6.q16: no images defined `./ddr-sbbt-3-28-mezzanine-e9670899fa.jpg' @ error/convert.c/ConvertImageCommand/3258`

Files that are having this issues have been copied to `/media/qnfs/kinkura/working/Problem_Tifs`

**Comment by gjost** [comment]
Images are too big.  I'll have to update the `policy.xml` file

**Comment by gjost** [comment]
Fixed in commit `c1c1bc2` on `ddr-cmdln` `develop` branch.
