### ISSUE TITLE
ddrimport file external files

### ISSUE THREAD

**Issue by sarabeckman** [denshoproject/ddr-cmdln#225]
Running `ddrimport file` on my local VM running V5.6.1_HQMA. 

I working on importing external mezzanine files for new interviews for `ddr-densho-1000`. I've included one of the CSVs for the external files below. The CSVs already have all the hashes and the external links from running `ddr-vhfileprep`. Usually I run `ddrimport file` without the files being present in the repository but with the new validation check I can't and it hashes the files which causes everything to slow down.

[fileimport.csv](https://github.com/denshoproject/ddr-cmdln/files/10551679/fileimport.csv)

**Comment by gjost** [comment]
Fixed in `ddr-cmdln` `master` branch commit `7a0e135` and pushed.

**Comment by GeoffFroh** [comment]
Unable to verify the fix -- related to https://github.com/denshoproject/ddr-cmdln/issues/226

**Comment by gjost** [comment]
The fix to https://github.com/denshoproject/ddr-cmdln/issues/226 should make this verifiable now.
